"""initial schema

Revision ID: 0ca585b7e74d
Revises: 
Create Date: 2026-10-02 07:27:33.764370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ca585b7e74d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('platform_admin', 'owner', 'attendant', 'customer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('assigned_lot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_assigned_lot_id'), 'users', ['assigned_lot_id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('lots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('owner_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_lots_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lots'))
    )
    op.create_index(op.f('ix_lots_owner_id'), 'lots', ['owner_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('plate', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vehicles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('user_id', 'plate', name='uq_vehicles_user_plate')
    )
    op.create_index(op.f('ix_vehicles_plate'), 'vehicles', ['plate'], unique=False)
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('attendant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('lot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.Enum('open', 'submitted', 'confirmed', name='shift_status'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_cash', sa.Integer(), nullable=True),
    sa.Column('declared_cash', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendant_id'], ['users.id'], name=op.f('fk_shifts_attendant_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], name=op.f('fk_shifts_confirmed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_shifts_lot_id_lots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )
    op.create_index(op.f('ix_shifts_attendant_id'), 'shifts', ['attendant_id'], unique=False)
    op.create_index(op.f('ix_shifts_lot_id'), 'shifts', ['lot_id'], unique=False)
    op.create_index('uq_shifts_open_attendant', 'shifts', ['attendant_id'], unique=True, postgresql_where=sa.text("status = 'open'"), sqlite_where=sa.text("status = 'open'"))
    op.create_table('tariffs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('lot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.Enum('hourly', 'daily', 'monthly', name='tariff_kind'), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('free_minutes', sa.Integer(), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('free_minutes >= 0', name=op.f('ck_tariffs_free_minutes_non_negative')),
    sa.CheckConstraint('rate >= 0', name=op.f('ck_tariffs_rate_non_negative')),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_tariffs_lot_id_lots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariffs'))
    )
    op.create_index(op.f('ix_tariffs_lot_id'), 'tariffs', ['lot_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('lot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_zones_lot_id_lots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones')),
    sa.UniqueConstraint('lot_id', 'name', name='uq_zones_lot_name')
    )
    op.create_index(op.f('ix_zones_lot_id'), 'zones', ['lot_id'], unique=False)
    op.create_table('spots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('lot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('zone_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('free', 'occupied', 'reserved', 'out_of_service', name='spot_status'), nullable=False),
    sa.Column('is_ev', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_spots_lot_id_lots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_spots_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spots')),
    sa.UniqueConstraint('lot_id', 'code', name='uq_spots_lot_code')
    )
    op.create_index(op.f('ix_spots_lot_id'), 'spots', ['lot_id'], unique=False)
    op.create_index(op.f('ix_spots_zone_id'), 'spots', ['zone_id'], unique=False)
    op.create_table('parking_sessions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('lot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('spot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('tariff_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('plate', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'cancelled', name='parking_session_status'), nullable=False),
    sa.Column('entry_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('opened_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('closed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], name=op.f('fk_parking_sessions_closed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_parking_sessions_lot_id_lots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], name=op.f('fk_parking_sessions_opened_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], name=op.f('fk_parking_sessions_spot_id_spots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], name=op.f('fk_parking_sessions_tariff_id_tariffs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_parking_sessions_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parking_sessions'))
    )
    op.create_index(op.f('ix_parking_sessions_lot_id'), 'parking_sessions', ['lot_id'], unique=False)
    op.create_index(op.f('ix_parking_sessions_plate'), 'parking_sessions', ['plate'], unique=False)
    op.create_index(op.f('ix_parking_sessions_user_id'), 'parking_sessions', ['user_id'], unique=False)
    op.create_index('uq_parking_sessions_open_plate', 'parking_sessions', ['lot_id', 'plate'], unique=True, postgresql_where=sa.text("status = 'open'"), sqlite_where=sa.text("status = 'open'"))
    op.create_table('payments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('lot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('kind', sa.Enum('parking', 'ev_charge', 'subscription', name='payment_kind'), nullable=False),
    sa.Column('method', sa.Enum('qpay', 'cash', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'expired', 'refunded', name='payment_status'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('commission_amount', sa.Integer(), nullable=False),
    sa.Column('parking_session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('ev_session_id', sa.BigInteger(), nullable=True),
    sa.Column('recorded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('shift_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('qpay_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('qpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method <> 'cash' OR recorded_by_id IS NOT NULL", name=op.f('ck_payments_cash_has_attendant')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payments_amount_non_negative')),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_payments_lot_id_lots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parking_session_id'], ['parking_sessions.id'], name=op.f('fk_payments_parking_session_id_parking_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_payments_recorded_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_payments_shift_id_shifts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_payments_idempotency_key')),
    sa.UniqueConstraint('qpay_invoice_id', name=op.f('uq_payments_qpay_invoice_id')),
    sa.UniqueConstraint('qpay_payment_id', name=op.f('uq_payments_qpay_payment_id'))
    )
    op.create_index(op.f('ix_payments_lot_id'), 'payments', ['lot_id'], unique=False)
    op.create_index(op.f('ix_payments_method'), 'payments', ['method'], unique=False)
    op.create_index(op.f('ix_payments_paid_at'), 'payments', ['paid_at'], unique=False)
    op.create_index(op.f('ix_payments_parking_session_id'), 'payments', ['parking_session_id'], unique=False)
    op.create_index(op.f('ix_payments_shift_id'), 'payments', ['shift_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('payment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_payment_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_events_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events'))
    )
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=False)
    # ### end Alembic commands ###
    # users <-> lots reference each other, so this FK is added after both tables exist.
    op.create_foreign_key(
        op.f('fk_users_assigned_lot_id_lots'), 'users', 'lots', ['assigned_lot_id'], ['id'], ondelete='SET NULL'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_assigned_lot_id_lots'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_shift_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_parking_session_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_paid_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_lot_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('uq_parking_sessions_open_plate', table_name='parking_sessions', postgresql_where=sa.text("status = 'open'"), sqlite_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_parking_sessions_user_id'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_plate'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_lot_id'), table_name='parking_sessions')
    op.drop_table('parking_sessions')
    op.drop_index(op.f('ix_spots_zone_id'), table_name='spots')
    op.drop_index(op.f('ix_spots_lot_id'), table_name='spots')
    op.drop_table('spots')
    op.drop_index(op.f('ix_zones_lot_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_tariffs_lot_id'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index('uq_shifts_open_attendant', table_name='shifts', postgresql_where=sa.text("status = 'open'"), sqlite_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_shifts_lot_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_attendant_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_lots_owner_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_assigned_lot_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    for enum_name in (
        'user_role', 'spot_status', 'tariff_kind', 'parking_session_status',
        'payment_kind', 'payment_method', 'payment_status', 'shift_status',
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
