"""staff username and password

Revision ID: 9ddc12eafec8
Revises: 0ca585b7e74d
Create Date: 2026-10-02 07:38:31.766821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ddc12eafec8'
down_revision: Union[str, Sequence[str], None] = '0ca585b7e74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###
    op.create_check_constraint(op.f('ck_users_has_login'), 'users', 'phone IS NOT NULL OR username IS NOT NULL')


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f('ck_users_has_login'), 'users', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
